// GENERATED by tools/prep-photos.py - do not edit by hand.
//
// Keyed by the two-digit step number. A step with no entry renders
// without a photograph rather than with a broken one, so the six can
// arrive a few at a time.
const PHOTOS = {
  "01": {
    "h": 886,
    "src": "/process/01.jpg",
    "w": 1400
  },
  "02": {
    "h": 1400,
    "src": "/process/02.jpg",
    "w": 1130
  },
  "03": {
    "h": 1284,
    "src": "/process/03.jpg",
    "w": 1400
  },
  "04": {
    "h": 1400,
    "src": "/process/04.jpg",
    "w": 1050
  },
  "05": {
    "h": 1050,
    "src": "/process/05.jpg",
    "w": 1400
  },
  "06": {
    "h": 1050,
    "src": "/process/06.jpg",
    "w": 1400
  }
};

export default PHOTOS;
