# -*- coding: utf-8 -*-
"""Prepare the process photographs for the web.

Drop the originals into myapp/photos-src/ named by the step they belong to -
01*.jpg for FORM, 02* for CIRCUIT, and so on - then run:

    python tools/prep-photos.py

The originals are phone photographs, several thousand pixels on a side and a
few megabytes each. This page is opened from a QR card at a festival, usually
on mobile data, so they are capped at LONG_EDGE and re-encoded before they ever
reach public/. Everything here is derived: photos-src/ and public/process/ are
both out of the repository, and re-running rebuilds them.

Writing the pixel dimensions out to src/photos.js is the point of the script as
much as the resizing is. The <img> needs them to reserve the right space before
the file arrives; without that, six photographs of mixed orientation shove the
text around as each one loads.
"""
import json
import os
from PIL import Image, ImageOps

LONG_EDGE = 1400      # covers a full-width photo on a 3x phone screen
QUALITY = 78          # visibly clean at this size; ~250KB a photo

# A few photographs are also shown inside the drifting shapes on the opening
# screen, at about 120 CSS pixels across. Those are the only images on the page
# a visitor has not asked for yet - they load before anything is tapped - so
# they get their own small copy rather than the full-size file scaled down in
# the browser. 320px covers a 3x screen at that size.
THUMB_KEYS = {'entrance1', '04'}
THUMB_EDGE = 320
THUMB_QUALITY = 72

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)
SRC = os.path.join(APP, 'photos-src')
OUT = os.path.join(APP, 'public', 'process')
MANIFEST = os.path.join(APP, 'src', 'photos.js')

os.makedirs(OUT, exist_ok=True)

# Cleared first, so a photo dropped from photos-src actually disappears from the
# site instead of leaving its old file behind for the next deploy to serve.
for stale in os.listdir(OUT):
    os.remove(os.path.join(OUT, stale))

photos = {}

for name in sorted(os.listdir(SRC)):
    stem, ext = os.path.splitext(name)
    if ext.lower() not in ('.jpg', '.jpeg', '.png', '.webp'):
        continue
    # Everything before the first dash is the key: "03-assembly.jpg" is step
    # 03, "location.jpg" is the location card. Anything after the dash is a note
    # to whoever is looking in the folder and is ignored here.
    key = stem.split('-')[0].strip().lower()
    if not key.isalnum():
        print('skipping %s: name must start with a key, then a dash' % name)
        continue

    with Image.open(os.path.join(SRC, name)) as im:
        # Phone photographs carry their rotation in EXIF rather than in the
        # pixels. Without this the frame shots come out on their side.
        im = ImageOps.exif_transpose(im)
        im.thumbnail((LONG_EDGE, LONG_EDGE), Image.LANCZOS)
        im.convert('RGB').save(
            os.path.join(OUT, key + '.jpg'),
            'JPEG', quality=QUALITY, optimize=True, progressive=True,
        )
        photos[key] = {'src': '/process/%s.jpg' % key, 'w': im.width, 'h': im.height}

        if key in THUMB_KEYS:
            t = im.copy()
            t.thumbnail((THUMB_EDGE, THUMB_EDGE), Image.LANCZOS)
            t.convert('RGB').save(
                os.path.join(OUT, key + '-t.jpg'),
                'JPEG', quality=THUMB_QUALITY, optimize=True,
            )
            photos[key]['thumb'] = '/process/%s-t.jpg' % key

    kb = os.path.getsize(os.path.join(OUT, key + '.jpg')) / 1024
    print('%s  %sx%s  %.0fKB' % (key, im.width, im.height, kb))

with open(MANIFEST, 'w', encoding='utf-8', newline='') as f:
    f.write(
        '// GENERATED by tools/prep-photos.py - do not edit by hand.\n'
        '//\n'
        '// Keyed by the two-digit step number. A step with no entry renders\n'
        '// without a photograph rather than with a broken one, so the six can\n'
        '// arrive a few at a time.\n'
        'const PHOTOS = '
    )
    f.write(json.dumps(photos, indent=2, sort_keys=True))
    f.write(';\n\nexport default PHOTOS;\n')

print('\n%d photo(s) -> public/process/, manifest -> src/photos.js' % len(photos))
